import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Chart App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1>Blockhouse Chart App</h1>
        <h2>Developed by Kieran Nebel</h2>
        {children}
      </body>
    </html>
  );
}
